<?php
include("../koneksi.php");
session_start();
	$ip= $_SERVER['REMOTE_ADDR'];
	$useredit=$_SESSION['userGKJ'];
	$nokk=$_POST['nokk'];
	$sql 	= "SELECT A.LOTCODE, B.CODE AS NO_ORDER,B.ORDERPARTNERBRANDCODE,B.LONGDESCRIPTION AS BUYER, B.LEGALNAME1 AS LANGGANAN, B.ITEMDESCRIPTION AS JENIS_KAIN,
	B.PO_HEADER AS PO_HEADER,B.PO_LINE AS PO_LINE, C.PRODUCTIONDEMANDCODE AS NO_LOT,TRIM(D.LONGDESCRIPTION) AS WARNA FROM BALANCE A 
LEFT JOIN 
	(SELECT SALESORDER.CODE,SALESORDER.ORDERPARTNERBRANDCODE,ORDERPARTNERBRAND.LONGDESCRIPTION,BUSINESSPARTNER.LEGALNAME1,
	SALESORDER.EXTERNALREFERENCE AS PO_HEADER,SALESORDERLINE.EXTERNALREFERENCE AS PO_LINE, SALESORDERLINE.ITEMDESCRIPTION, 
	SALESORDERLINE.ITEMTYPEAFICODE, SALESORDERLINE.SUBCODE01, SALESORDERLINE.SUBCODE02, SALESORDERLINE.SUBCODE03,
	SALESORDERLINE.SUBCODE04, SALESORDERLINE.SUBCODE05, SALESORDERLINE.SUBCODE06, SALESORDERLINE.SUBCODE07,
	SALESORDERLINE.SUBCODE08, SALESORDERLINE.SUBCODE09, SALESORDERLINE.SUBCODE10
	FROM SALESORDER SALESORDER
	LEFT JOIN SALESORDERLINE SALESORDERLINE ON SALESORDER.CODE = SALESORDERLINE.SALESORDERCODE
	LEFT JOIN ORDERPARTNERBRAND ORDERPARTNERBRAND ON SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNERBRAND.ORDPRNCUSTOMERSUPPLIERCODE AND SALESORDER.ORDERPARTNERBRANDCODE = ORDERPARTNERBRAND.CODE
	LEFT JOIN ORDERPARTNER ORDERPARTNER ON SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
	LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
	GROUP BY SALESORDER.CODE,SALESORDER.ORDERPARTNERBRANDCODE,ORDERPARTNERBRAND.LONGDESCRIPTION,
	SALESORDER.EXTERNALREFERENCE,SALESORDERLINE.EXTERNALREFERENCE,SALESORDERLINE.ITEMDESCRIPTION,BUSINESSPARTNER.LEGALNAME1,
	SALESORDERLINE.ITEMTYPEAFICODE, SALESORDERLINE.SUBCODE01, SALESORDERLINE.SUBCODE02, SALESORDERLINE.SUBCODE03,
	SALESORDERLINE.SUBCODE04, SALESORDERLINE.SUBCODE05, SALESORDERLINE.SUBCODE06, SALESORDERLINE.SUBCODE07,
	SALESORDERLINE.SUBCODE08, SALESORDERLINE.SUBCODE09, SALESORDERLINE.SUBCODE10) B
ON A.PROJECTCODE = B.CODE AND 
A.ITEMTYPECODE = B.ITEMTYPEAFICODE AND 
A.DECOSUBCODE01 = B.SUBCODE01 AND
A.DECOSUBCODE02 = B.SUBCODE02 AND
A.DECOSUBCODE03 = B.SUBCODE03 AND
A.DECOSUBCODE04 = B.SUBCODE04 AND
A.DECOSUBCODE05 = B.SUBCODE05 AND
A.DECOSUBCODE06 = B.SUBCODE06 AND
A.DECOSUBCODE07 = B.SUBCODE07 AND
A.DECOSUBCODE08 = B.SUBCODE08 AND
A.DECOSUBCODE09 = B.SUBCODE09 AND
A.DECOSUBCODE10 = B.SUBCODE10
LEFT JOIN 
(SELECT PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE, PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE FROM 
	PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
	GROUP BY PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE) C
ON A.LOTCODE=C.PRODUCTIONORDERCODE
LEFT JOIN 
	(SELECT USERGENERICGROUP.CODE,USERGENERICGROUP.LONGDESCRIPTION FROM USERGENERICGROUP USERGENERICGROUP) D
ON A.DECOSUBCODE05=D.CODE
WHERE TRIM(A.LOTCODE)='$nokk'
LIMIT 1";
    $stmt=db2_exec($conn1,$sql, array('cursor'=>DB2_SCROLLABLE));
	$row = db2_fetch_assoc($stmt);
	if($rowdb2['PO_HEADER']!=''){
	$nopo=str_replace("'","''",$row['PO_HEADER']);}
	else{$nopo=str_replace("'","''",$row['PO_LINE']);}
    $jeniskain =str_replace("'","''",$row['JENIS_KAIN']);

    $sqlupdate 	= mysqli_query($con,"UPDATE tbl_bon_permintaan SET nokk='$_POST[nokk]', langganan='$row[LANGGANAN]', no_po='$nopo', no_order='$row[NO_ORDER]', jenis_kain='$jeniskain', warna='$row[WARNA]', no_lot='$row[NO_LOT]' WHERE id='$_POST[id]'");

    $sqlInsert=mysqli_query($con,"INSERT INTO tbl_log_bon_gkj SET
    proses='Edit No KK',
    detail_proses='Edit No KK menjadi $nokk ',
    user='$useredit',
    waktu_proses=now(),
    ip='$ip'");

    if($sqlupdate){
        echo "<script>window.location='ViewDetailBon-$_POST[bon]';</script>";
    }else{
		echo "Update Data Gagal";
	}
?>
